language: java
os: osx
git:
  depth: 3
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - darkklitos@gmail.com
addons:
  sonarcloud:
    organization: "gdaimon"
    token:
      secure: $SONAR_TOKEN
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Gdaimon_cupon-mercado-libre
deploy:
  provider: heroku
  api_key: ${HEROKU}
  app: cupon-mercado-libre
  on:
    branch: master
before_install:
  - chmod +x mvnw
